version: '2'
services:

  web-green:
    environment:
      - ENV_ENVIRONMENT=production
      - SERVICE_NAME=web-green
      -  "SERVICE_TAGS=master,web, green"
    extends:
      service: web
    restart: unless-stopped

  web-blue:
    environment:
      - ENV_ENVIRONMENT=production
      - SERVICE_NAME=web-blue
      - "SERVICE_TAGS=master,web, blue"
    extends:
      service: web
    restart: unless-stopped

  redis:
    restart: unless-stopped
    environment:
      - ENV_ENVIRONMENT=production

networks:
  mynet: