version: '2'
services:
  web:
    build: .
    ports:
     - "8080"
    networks:
      - mynet
    labels:
      - "com.workshop.web.description=Accounting webapp"
      - "com.workshop.web.version=v1"
    environment:
      - ENV_ENVIRONMENT=development
      - ENV_INCR_NAME=hit
  redis:
    image: redis:alpine
    networks:
      - mynet

networks:
  mynet:



