version: '2'
services:
  web:
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://logstash:5000"
  redis:
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://logstash:5000"